# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build and Publish
on: [push]

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  NuGetDirectory: ${{github.workspace}}/.nuget

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup .Net
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x

    - run: |
        github_sha_hash=${{ github.sha }}

        git_hash="${github_sha_hash:0:7}"

        printf -v jdate '%(%y%j.%H%m)T\n'

        echo "GIT_HASH=${git_hash}" >> "$GITHUB_ENV"
        echo "JDATE=${jdate}"       >> "$GITHUB_ENV"

    - run: |
        dotnet restore -s "https://api.nuget.org/v3/index.json"

        echo "JDate - ${JDATE}"
