name: Build and Publish
on: [push]

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup .Net
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x

    - name: Setup Environment Variables
      run: |
        github_sha_hash=${{ github.sha }}

        git_hash="${github_sha_hash:0:7}"

        printf -v jdate '%(%y%j.%H%m)T\n'

        echo "GIT_HASH=${git_hash}" >> "$GITHUB_ENV"
        echo "JDATE=${jdate}"       >> "$GITHUB_ENV"

    - name: Restore Nuget Packages
      run: dotnet restore --packages ./.nuget/packages -s "https://api.nuget.org/v3/index.json"

    - name: Clean
      run: dotnet clean --configuration Debug

    - name: Build Debug
      run: dotnet build --configuration Debug --no-restore --packages ./.nuget/packages
